name: 'Generate build manifest'
description: 'Generates a build manifest JSON based on refs / package.json'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  scm-info:
    description: 'Get information from SCM/GitHub'
    required: false
    default: 'true'
  package-info:
    description: 'Get information from package.json'
    required: false
    default: 'true'
  action-info:
    description: 'Write GitHub action info in the manifest'
    required: false
    default: 'true'
  package-json:
    description: 'package.json path (included package.json name)'
    required: false
    default: './package.json'
  dockerfile:
    description: 'Dockerfile path (included dockerfile name)'
    required: false
    default: './Dockerfile'
  append-dockerfile:
    description: 'Automatically append COPY command in Dockerfile'
    required: false
    default: 'true'
  manifest-file:
    description: 'Manifest filename'
    required: false
    default: 'build-manifest.json'
outputs:
  manifest-content:
    description: 'The content of the generated manifest'
runs:
  using: 'node20'
  main: 'dist/index.js'